apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beer-academy-frontend-ingress # Unique name for Angular Ingress
  namespace: beer-academy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod # Use staging for testing
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: beeracademy.mathiaskofod.dk
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: beer-academy-backend-service # <--- Points to your new Angular Service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beer-academy-frontend-service # <--- Points to your new Angular Service
                port:
                  number: 80
  tls:
    - hosts:
        - beeracademy.mathiaskofod.dk # <--- Your NEW Angular subdomain
        - www.beeracademy.mathiaskofod.dk # <--- Your NEW Angular subdomain
      secretName: beer-academy-tls-secret # Unique secret name for this certificate
